logging:
    level:
        org:
            flywaydb: DEBUG
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: krylov
        url: jdbc:postgresql://localhost:5432/postgres
        username: alexandr
    flyway:
        baseline-on-migrate: true
        enabled: true
        locations: classpath:db/migration
        schemas: public
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
telegram:
    bot:
        token: 7550915997:AAGTnrgzFlHbQA0xDg-ylnYr7u2OjeRUfvU
        username: loading_parcels_bot
